cmake_minimum_required(VERSION 3.16)

set(N 8)
set_property(GLOBAL PROPERTY SOLUTION_COUNT 0)

# Check if placing queen at (col, row) conflicts with existing queens
# board[i] = row of queen in column i
function(is_safe board col row out_var)
    if(col EQUAL 0)
        set(${out_var} TRUE PARENT_SCOPE)
        return()
    endif()

    math(EXPR last "${col} - 1")
    foreach(c RANGE 0 ${last})
        list(GET board ${c} r)

        # Same row?
        if(r EQUAL row)
            set(${out_var} FALSE PARENT_SCOPE)
            return()
        endif()

        # Same diagonal? |row_diff| == |col_diff|
        math(EXPR dr "${r} - ${row}")
        math(EXPR dc "${c} - ${col}")
        if(dr LESS 0)
            math(EXPR dr "0 - ${dr}")
        endif()
        if(dc LESS 0)
            math(EXPR dc "0 - ${dc}")
        endif()

        if(dr EQUAL dc)
            set(${out_var} FALSE PARENT_SCOPE)
            return()
        endif()
    endforeach()

    set(${out_var} TRUE PARENT_SCOPE)
endfunction()

function(print_board board num)
    message("=== Solution ${num} ===")
    math(EXPR max "${N} - 1")
    foreach(row RANGE 0 ${max})
        set(line "")
        foreach(col RANGE 0 ${max})
            list(GET board ${col} queen_row)
            if(queen_row EQUAL row)
                string(APPEND line "Q ")
            else()
                string(APPEND line ". ")
            endif()
        endforeach()
        message("${line}")
    endforeach()
    message("")
endfunction()

function(solve board col)
    if(col EQUAL ${N})
        get_property(cnt GLOBAL PROPERTY SOLUTION_COUNT)
        math(EXPR cnt "${cnt} + 1")
        set_property(GLOBAL PROPERTY SOLUTION_COUNT ${cnt})
        print_board("${board}" ${cnt})
        return()
    endif()

    math(EXPR max_row "${N} - 1")
    foreach(row RANGE 0 ${max_row})
        is_safe("${board}" ${col} ${row} safe)
        if(safe)
            set(new_board ${board})
            list(APPEND new_board ${row})
            math(EXPR next_col "${col} + 1")
            solve("${new_board}" ${next_col})
        endif()
    endforeach()
endfunction()

message("Solving ${N}-Queens...")
message("")
solve("" 0)
get_property(total GLOBAL PROPERTY SOLUTION_COUNT)
message("Total solutions: ${total}")
