IF(CMAKE_SYSTEM_PROCESSOR MATCHES "ppc64|powerpc64" OR CMAKE_SYSTEM_NAME MATCHES AIX)
    message("On PPC")
ELSE()
    message("Not PPC")
ENDIF()
message("processor ${CMAKE_SYSTEM_PROCESSOR}")
message("name: ${CMAKE_SYSTEM_NAME}")

if(CMAKE_SYSTEM_PROCESSOR MATCHES "ppc64|powerpc64")
    message("Match")
else()
    message("Not Match")
endif()

if(CMAKE_SYSTEM_NAME MATCHES AIX)
    message("Match AIX")
else()
    message("Not Match AIX")
endif()
