set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}")
include(ExtractValidFlags.cmake)
foreach(_cxx1x_flag -std=c++20)
  extract_valid_cxx_flags(_cxx1x_flag_supported ${_cxx1x_flag})
  message("${_cxx1x_flag} is ${_cxx1x_flag_supported}")
  if(_cxx1x_flag_supported)
    set(CXX1XCXXFLAGS ${_cxx1x_flag})
    break()
  endif()
endforeach()
    if(_cxx1x_flag_supported)
      set(CXX1XCXXFLAGS ${_cxx1x_flag})
      break()
    endif()
  endforeach()
