message(STATUS "Checking version for package: ${PACKAGE_FIND_NAME}")
set(PACKAGE_VERSION "2.0.0")

# Simple version parsing for our mock
set(PACKAGE_VERSION_MAJOR 2)
set(PACKAGE_VERSION_MINOR 0)
set(PACKAGE_VERSION_PATCH 0)

if("${PACKAGE_FIND_VERSION_MAJOR}" EQUAL "${PACKAGE_VERSION_MAJOR}")
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    if ("${PACKAGE_FIND_VERSION}" STREQUAL "${PACKAGE_VERSION}")
        set(PACKAGE_VERSION_EXACT TRUE)
    endif()
else()
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
endif()